artifact_location: file:///Users/omtailor/Quanutum_MS_Pipeline/tracking/mlflow/benchmarks/369434848088660737
creation_time: 1759343377189
experiment_id: '369434848088660737'
last_update_time: 1759343377189
lifecycle_stage: active
name: dft_benchmarks
