artifact_uri: file:///Users/omtailor/Quanutum_MS_Pipeline/tracking/mlflow/benchmarks/369434848088660737/d297732bce4e459ea2d33b6193cb0c94/artifacts
end_time: 1759351717589
entry_point_name: ''
experiment_id: '369434848088660737'
lifecycle_stage: active
run_id: d297732bce4e459ea2d33b6193cb0c94
run_name: qe-benchmark-QAL-0001
source_name: ''
source_type: 4
source_version: ''
start_time: 1759349771577
status: 4
tags: []
user_id: omtailor
