artifact_uri: file:///Users/omtailor/Quanutum_MS_Pipeline/tracking/mlflow/benchmarks/369434848088660737/c75dad0f669049b9b784ec10fcb29e46/artifacts
end_time: 1759343391090
entry_point_name: ''
experiment_id: '369434848088660737'
lifecycle_stage: active
run_id: c75dad0f669049b9b784ec10fcb29e46
run_name: qe-storage-QAL-0001
source_name: ''
source_type: 4
source_version: ''
start_time: 1759343391080
status: 3
tags: []
user_id: omtailor
