artifact_uri: file:///Users/omtailor/Quanutum_MS_Pipeline/tracking/mlflow/benchmarks/369434848088660737/bb5fd3268dc04ba3b89c815ebf6f21b5/artifacts
end_time: 1759356052291
entry_point_name: ''
experiment_id: '369434848088660737'
lifecycle_stage: active
run_id: bb5fd3268dc04ba3b89c815ebf6f21b5
run_name: qe-benchmark-BENCH-RELAX-0001
source_name: ''
source_type: 4
source_version: ''
start_time: 1759355410353
status: 3
tags: []
user_id: omtailor
