artifact_uri: file:///Users/omtailor/Quanutum_MS_Pipeline/tracking/mlflow/benchmarks/369434848088660737/09768ff36de0475eaff97e55765d3ea0/artifacts
end_time: 1759354300673
entry_point_name: ''
experiment_id: '369434848088660737'
lifecycle_stage: active
run_id: 09768ff36de0475eaff97e55765d3ea0
run_name: qe-benchmark-QAL-0001
source_name: ''
source_type: 4
source_version: ''
start_time: 1759354287354
status: 3
tags: []
user_id: omtailor
